### ISSUE TITLE
README.md missing from distribution. Can't install from PyPI

### ISSUE THREAD

**Issue by mobiusklein** [percevalw/treeprinter#1]
The setup script requires the file `README.md`, but this file isn't automatically included in the distribution tarball. Since the file is missing, installation fails.

```python
Collecting treeprinter
  Downloading treeprinter-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\j~1\appdata\local\temp\pip-build-i8_cge\treeprinter\setup.py", line 24, in <module>
        f = open('README.md')
    IOError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by percevalw** [comment]
Thanks for the issue, the README is now included in the tarball
